apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-uf6bhzcsgklxfii0i2jal
    service.beta.kubernetes.io/backend-type: eni
  labels:
    app: chaosblade-box
  name: chaosblade-box
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: chaosblade-box
  sessionAffinity: None
  type: LoadBalancer
